config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'home#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :questions do
    resources :answers
  end
  resources :answers, only: [] do
    post "upvote" , to: "votes#upvote", as: :upvote
    post "downvote" , to: "votes#downvote", as: :downvote
  end
  resources :topics
 
  resources :home ,only: [:account_not_approved] do 
    get :account_not_approved, on: :collection
  end
end
        

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <%= link_to 'Quora', root_path, class: 'navbar-brand' %>
  <!-- Links -->
  <div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav ">
    <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'My Questions', questions_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Ask Question', new_question_path, class: 'nav-link'  %>
      </li>
      
      <li class="nav-item">
        <%= link_to 'My profile', edit_user_registration_path, class: 'nav-link'  %>
      </li>
    <% else %>

      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Admin Login', admin_user_session_path, class: 'nav-link' %>
      </li>
      
    <% end %>
  </ul>
</div>
  <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'nav-link text-white' %>
  <% end %>

</nav>