config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'home#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :questions do
    resources :answers
  end
  resources :answers, only: [] do
    post "upvote" , to: "votes#upvote", as: :upvote
    post "downvote" , to: "votes#downvote", as: :downvote
  end
  resources :topics
 
  resources :home ,only: [:account_not_approved] do 
    get :account_not_approved, on: :collection
  end
end
        

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_to_interest_page
  before_action :check_account_status, only: [:index]
  
  def index
    @answer = Answer.new
    #@image = @answer.images.build
    @vote = Vote.new
    @questions = Question.includes(:topics, :answers, answers: :votes).where('topics.id IN (?)', current_user&.topics&.ids).references(:topic)
    session[:status_return_to] = nil
  end

  def account_not_approved
  end

  private
    def redirect_to_interest_page
      if current_user && current_user.topics.blank?
        session[:return_to] = topics_path
        if current_user.present? && session[:return_to].present?
          redirect_to session[:return_to]
        end 
      end
    end

    def check_account_status
      if current_user.present? && ( current_user.pending? || current_user.rejected? )
        flash[:notice] = "Your account is #{current_user.status}. please contact to admin"
        sign_out current_user
        redirect_to account_not_approved_home_index_path and return 
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_image_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container ">
  <% @questions.each do |que| %>
    <% answer = que.answers.new %>
    <% answer.images.build %>

    <%= form_with model: answer, url: question_answers_path(que), method: 'post', remote: true do |f| %>
      <div class="jumbotron w-75">
        <h5 class="h1 Bootstrap heading"><%= que.question_title %></h5>
        <ul id="answers-list-<%= que.id %>">
          <% if que.answers.present? %>  
            <%= render partial: 'answers/answer', locals: {answers: que.answers } %>
          <% end %>
        </ul>
        <a href="javascript:void(0)" class="show-hide-answer btn btn-primary">Answer</a>
        <div class="ans-block" style="display: none;"><br>
          <%= f.text_area :ans_content ,:cols => 50, class: 'ans_content_text' %><br>
          <span class="error-msg text-danger" style="display: none;">Answer can't be blank. </span>
          <br>
          
          <div id='tasks'>
            <%= f.fields_for :images do |image| %>
              <%= render 'image_fields', :f => image %>
            <% end %>
            <div class='links'>
              <%= link_to_add_association 'add image', f, :images %>
            </div>
          </div>
          <%= f.submit 'Submit Answer', class: 'btn btn-primary' %><br>
        </div>

      </div>
    <% end %>
  <% end %>
</div>