config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'home#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :questions do
    resources :answers
  end
  resources :answers, only: [] do
    post "upvote" , to: "votes#upvote", as: :upvote
    post "downvote" , to: "votes#downvote", as: :downvote
  end
  resources :topics
 
  resources :home ,only: [:account_not_approved] do 
    get :account_not_approved, on: :collection
  end
end
        

app/models/answer.rb
class Answer < ApplicationRecord
  # validations
  validates :ans_content, presence: true
  
  # Associations
  belongs_to :question  
  has_many :votes 
  has_many :images, as: :imageable#, inverse_of: :image
  
  accepts_nested_attributes_for :images, allow_destroy: true
  
  # Callbacks
  after_create :send_notification_user

  def up_votes
    self.votes.where(vote_type: Vote.vote_types[:upvote])
  end

  def down_votes
    self.votes.where(vote_type: Vote.vote_types[:downvote])
  end



  def send_notification_user
    UserMailer.answer_notification(self.question.user).deliver_now
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answers = @question.answers
    respond_to do |format|
      if @answer.save
        format.html {redirect_to root_path}
        format.js{}
      else
        format.html {redirect_to root_path}
        format.js{}
      end
    end
  end
  

  private
    def answer_params
      params.require(:answer).permit(:ans_content, images_attributes:[:image])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<% if answers.present? %>
    <% answers.each do |ans| %>
      <% next if ans.new_record? %>
      <br><li> <%= ans.ans_content %></li>
      <p>

      <% if ans.images.present? %> 
        <% ans.images.each do |image| %>
          <%= image_tag image.image.url, width: 700 %>
        <% end %>
      <% end %>

      </p>
      <div class="row">
        <div id="like-<%= ans.id%>">
          <span><%= ans.up_votes.size %></span>
          <% if ans.up_votes.pluck(:user_id).include?(current_user.id) %> 
            <%= link_to answer_upvote_path(ans.id, dislike: true), method: :post,remote: true  do %>
              <i class="far fa-thumbs-up"></i>
            <% end %>
          <% else %>
            <%= link_to answer_upvote_path(ans.id), method: :post,remote: true do %>
              <i class="far fa-thumbs-up"></i>
            <% end %>
          <% end %>

        </div>
        <div id="unlike-<%= ans.id%>" class="ml-auto">
          <span><%= ans.down_votes.size %></span>
          <% if ans.down_votes.pluck(:user_id).include?(current_user.id) %> 
            <%= link_to answer_downvote_path(ans.id, undislike: true), method: :post,remote: true do %>
            <i class="far fa-thumbs-down"></i>
            <% end %>
          <% else %>
            <%= link_to answer_downvote_path(ans.id), method: :post,remote: true do %>
              <i class="far fa-thumbs-down"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
<% else %>
    <li> No answer yet</li>
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  jQuery('.error-msg').show();
<% else %>
  var question_id = "<%= @question.id %>";
  jQuery('#answers-list-'+question_id).children().remove()
  jQuery('#answers-list-'+question_id).append("<%= escape_javascript(render(:partial => 'answer', :locals=> {answers: @answers})) %>");
  jQuery('.ans_content_text').val('')
<% end %>
  $('#addNewFormation').click(function(){
        $('div#formationSet').append('<div class ="FormationsForm"><input type="text" class="input-large" placeholder="Caption">'+
            '<button class="removeNewFormation" type="button">remove</button>    </div>');
    });
  $("div#formationSet").on('click', '.removeNewFormation', function(){
        $(this).closest('.FormationsForm').remove();
    });